---

state: present
app: fevermap
project_name: fevermap
env: staging
jenkins_source_repository_ref: 'main'
jenkins_source_repository_url: 'https://github.com/TouqeerHussain/fevermap.git'
jenkins_replicas: 1
create_jenkins: true
modify_default_jenkins: false
